export const ACTIVITY_CATEGORIES = [
  "running",
  "cycling",
  "hiking",
  "swimming",
  "gym",
  "winter_sports",
  "team_sports",
  "racket_sports",
  "other",
] as const;

export type ActivityCategory = (typeof ACTIVITY_CATEGORIES)[number];

export const ACTIVITY_CATEGORY_LABEL: Record<ActivityCategory, string> = {
  running: "Running",
  cycling: "Cycling",
  hiking: "Hiking",
  swimming: "Swimming",
  gym: "Gym",
  winter_sports: "Winter sports",
  team_sports: "Team sports",
  racket_sports: "Racket sports",
  other: "Other",
};

// sportType (Garmin typeKey) -> categoría. Derivado del árbol completo de
// GET /activity-service/activity/activityTypes (154 typeKey, confirmado en vivo
// 2026-09-02, docs/garmin-api.md): cada typeKey resuelto subiendo su parentTypeId hasta
// una de las 16 categorías raíz de Garmin, y esas 16 mapeadas a las 9 de acá (las que no
// tienen ícono propio en esta pasada — walking, multi_sport, steps, diving, safety,
// para_sports, water_sports — caen en "other"). Un sportType nuevo que Garmin agregue cae
// en "other" por el fallback de getActivityCategory, no rompe nada.
const SPORT_TYPE_TO_CATEGORY: Record<string, ActivityCategory> = {
  running: "running",
  cycling: "cycling",
  hiking: "hiking",
  other: "other",
  mountain_biking: "cycling",
  trail_running: "running",
  street_running: "running",
  track_running: "running",
  walking: "other",
  road_biking: "cycling",
  indoor_cardio: "gym",
  strength_training: "gym",
  casual_walking: "other",
  speed_walking: "other",
  treadmill_running: "running",
  cyclocross: "cycling",
  downhill_biking: "cycling",
  track_cycling: "cycling",
  recumbent_cycling: "cycling",
  indoor_cycling: "cycling",
  swimming: "swimming",
  lap_swimming: "swimming",
  open_water_swimming: "swimming",
  fitness_equipment: "gym",
  elliptical: "gym",
  stair_climbing: "gym",
  indoor_rowing: "gym",
  mountaineering: "other",
  wind_kite_surfing: "other",
  horseback_riding: "other",
  driving_general: "other",
  flying: "other",
  whitewater_rafting_kayaking: "other",
  inline_skating: "other",
  golf: "other",
  multi_sport: "other",
  steps: "other",
  bmx: "cycling",
  hunting_fishing: "other",
  sky_diving: "other",
  rc_drone: "other",
  rock_climbing: "other",
  hang_gliding: "other",
  wingsuit_flying: "other",
  gravel_cycling: "cycling",
  diving: "other",
  single_gas_diving: "other",
  multi_gas_diving: "other",
  gauge_diving: "other",
  apnea_diving: "other",
  floor_climbing: "other",
  stop_watch: "other",
  virtual_ride: "cycling",
  virtual_run: "running",
  obstacle_run: "running",
  apnea_hunting: "other",
  indoor_running: "running",
  safety: "other",
  assistance: "other",
  incident_detected: "other",
  pilates: "gym",
  ccr_diving: "other",
  auto_racing: "other",
  yoga: "gym",
  breathwork: "other",
  winter_sports: "winter_sports",
  snowmobiling_ws: "winter_sports",
  snow_shoe_ws: "winter_sports",
  skating_ws: "winter_sports",
  backcountry_skiing_snowboarding_ws: "winter_sports",
  skate_skiing_ws: "winter_sports",
  cross_country_skiing_ws: "winter_sports",
  resort_skiing_snowboarding_ws: "winter_sports",
  indoor_climbing: "gym",
  bouldering: "gym",
  e_bike_mountain: "cycling",
  e_bike_fitness: "cycling",
  hiit: "gym",
  ultra_run: "running",
  e_sport: "other",
  motorcycling_v2: "other",
  motocross_v2: "other",
  atv_v2: "other",
  transition_v2: "other",
  swimToBikeTransition_v2: "other",
  bikeToRunTransition_v2: "other",
  runToBikeTransition_v2: "other",
  hunting: "other",
  hand_cycling: "cycling",
  indoor_hand_cycling: "cycling",
  para_sports: "other",
  wheelchair_push_run: "other",
  wheelchair_push_walk: "other",
  meditation: "other",
  backcountry_skiing: "winter_sports",
  backcountry_snowboarding: "winter_sports",
  disc_golf: "other",
  team_sports: "team_sports",
  cricket: "team_sports",
  rugby: "team_sports",
  ice_hockey: "team_sports",
  field_hockey: "team_sports",
  lacrosse: "team_sports",
  volleyball: "team_sports",
  ultimate_disc: "team_sports",
  softball: "team_sports",
  soccer: "team_sports",
  american_football: "team_sports",
  basketball: "team_sports",
  baseball: "team_sports",
  racket_sports: "racket_sports",
  table_tennis: "racket_sports",
  platform_tennis: "racket_sports",
  racquetball: "racket_sports",
  squash: "racket_sports",
  badminton: "racket_sports",
  pickleball: "racket_sports",
  paddelball: "racket_sports",
  tennis_v2: "racket_sports",
  water_sports: "other",
  boating_v2: "other",
  fishing_v2: "other",
  kayaking_v2: "other",
  kiteboarding_v2: "other",
  offshore_grinding_v2: "other",
  onshore_grinding_v2: "gym",
  paddling_v2: "other",
  whitewater_rafting_v2: "other",
  rowing_v2: "other",
  sailing_v2: "other",
  stand_up_paddleboarding_v2: "other",
  surfing_v2: "other",
  water_tubing: "other",
  windsurfing_v2: "other",
  wakeboarding_v2: "other",
  wakesurfing: "other",
  waterskiing: "other",
  boxing: "other",
  archery: "other",
  mixed_martial_arts: "other",
  overland: "other",
  snorkeling: "other",
  resort_skiing: "winter_sports",
  resort_snowboarding: "winter_sports",
  dance: "gym",
  jump_rope: "gym",
  mobility: "gym",
  enduro_mtb: "cycling",
  rucking: "hiking",
  pool_apnea: "other",
  e_enduro_mtb: "cycling",
  fall_detected: "other",
  cross_country_indoor_skiing: "gym",
};

export function getActivityCategory(sportType: string | null): ActivityCategory {
  return SPORT_TYPE_TO_CATEGORY[sportType ?? ""] ?? "other";
}

export function getSportTypesForCategory(category: ActivityCategory): string[] {
  return Object.entries(SPORT_TYPE_TO_CATEGORY)
    .filter(([, cat]) => cat === category)
    .map(([sportType]) => sportType);
}
